name: Build and Deploy Scorecard

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Build project
      run: msbuild games/scorecard.sln /p:Configuration=Debug

    - name: Copy full build output to deploy folder
      run: |
        mkdir deploy
        xcopy games\scorecard\bin\Debug deploy\ /E /I /Y

    - name: Commit and push to deploy branch
      run: |
        cd deploy
        git init
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "Deploy full build output"
        git branch -M deploy
        git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git push --force origin deploy
